%% This script compares the tidal harmonic decomposition between t_tide 
% (in MATLAB) and pytide
% In particular, it compares the data generated by the script
% harmonic_analysis.py
%%

% Read the data generated by pytide 

data = importdata('data/SL_DH_decomposed.csv',',',1);
time = datetime(data.textdata(2:end,2),'InputFormat','yyyy-MM-dd HH:mm:ss.S');
y = year(time);
%%

rec = y*0;


for i = 1996:2015
    
    [TIDESTRUC,XOUT]=t_tide(data.data(y==i,1)-694.6,'interval',1/6,'start time',[i, 1, 1, 0, 0, 0],'synthesis',1);
    rec(y==i) = XOUT; 
end

%%

figure (1)
plot(time(1:2000),data.data(1:2000,1)-694.6,'b')
hold on
plot(time(1:2000),rec(1:2000),'g')
plot(time(1:2000),data.data(1:2000,2),'r--')
%%
figure(2)
scatter(rec,data.data(:,2))

%%
figure(3)
plot(time(1:2000),data.data(1:2000,1)-rec(1:2000)-694.6,'b')
hold on
plot(time(1:2000),data.data(1:2000,1)-data.data(1:2000,2)-694.6,'r')


%%
figure(4) 
scatter(data.data(1:2000,1)-rec(1:2000)-694.6,data.data(1:2000,1)-data.data(1:2000,2)-694.6)
